In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import os
os.getcwd()
import pandas as pd

df = pd.read_csv(r"archive 1.zip")
print("Dataset loaded successfully")

Dataset loaded successfully

In [3]:
# shows full dataframe or dataset records with all colums 
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,1/3/2023,1/7/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,1/5/2023,1/12/2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,10190,US-2026-143259,12/30/2026,1/3/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
10190,10191,US-2026-115427,12/30/2026,1/3/2027,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750
10191,10192,US-2026-156720,12/30/2026,1/3/2027,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
10192,10193,US-2026-143259,12/30/2026,1/3/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
10193,10194,CA-2026-143500,12/30/2026,1/3/2027,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

In [4]:
# First 5 rows
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,1/3/2023,1/7/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,1/5/2023,1/12/2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [5]:
# Last 5 rows
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
10189,10190,US-2026-143259,12/30/2026,1/3/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
10190,10191,US-2026-115427,12/30/2026,1/3/2027,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750
10191,10192,US-2026-156720,12/30/2026,1/3/2027,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
10192,10193,US-2026-143259,12/30/2026,1/3/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
10193,10194,CA-2026-143500,12/30/2026,1/3/2027,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

In [6]:
# Random 5 rows
df.sample(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2763,2764,US-2024-162950,6/28/2024,7/3/2024,Second Class,DW-13585,Dorothy Wardle,Corporate,United States,Troy,...,45373,East,OFF-PA-10003177,Office Supplies,Paper,Xerox 1999,15.552,3,0.2,5.4432
3616,3617,US-2024-126466,11/9/2024,11/13/2024,Standard Class,JO-15550,Jesus Ocampo,Home Office,United States,Roseville,...,95661,West,OFF-FA-10000490,Office Supplies,Fasteners,"OIC Binder Clips, Mini, 1/4"" Capacity, Black",2.480,2,0.0,1.1656
6412,6413,US-2025-133711,11/26/2025,11/29/2025,First Class,MC-17425,Mark Cousins,Corporate,United States,Mobile,...,36608,South,OFF-PA-10001685,Office Supplies,Paper,Easy-staple paper,70.980,7,0.0,34.7802
7560,7561,US-2026-128755,5/4/2026,5/8/2026,Standard Class,MK-18160,Mike Kennedy,Consumer,United States,Newport News,...,23602,South,OFF-ST-10001291,Office Supplies,Storage,Tenex Personal Self-Stacking Standard File Box...,16.910,1,0.0,4.5657
2972,2973,US-2024-133396,8/13/2024,8/15/2024,First Class,GK-14620,Grace Kelly,Corporate,United States,Greensboro,...,27405,South,OFF-AR-10001446,Office Supplies,Art,Newell 309,64.680,7,0.2,8.0850

# Dataset Dimensions

In [7]:
print("Dataset shape:",df.shape)
print("Number of Rows:",df.shape[0])
print("Number of columns:",df.shape[1])
print("Total Elements:",df.size)

Dataset shape: (10194, 21)
Number of Rows: 10194
Number of columns: 21
Total Elements: 214074

In [9]:
# Columns name
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country/Region', 'City',
       'State/Province', 'Postal Code', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [10]:
df.dtypes

Row ID              int64
Order ID           object
Order Date         object
Ship Date          object
Ship Mode          object
Customer ID        object
Customer Name      object
Segment            object
Country/Region     object
City               object
State/Province     object
Postal Code        object
Region             object
Product ID         object
Category           object
Sub-Category       object
Product Name       object
Sales             float64
Quantity            int64
Discount          float64
Profit            float64
dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: float64(3), int64(2), object(16)
memory usage: 1.6+ MB

# Statistical summary

In [13]:
df.describe()

             Row ID         Sales      Quantity      Discount        Profit
count  10194.000000  10194.000000  10194.000000  10194.000000  10194.000000
mean    5097.500000    228.225854      3.791838      0.155385     28.673417
std     2942.898656    619.906839      2.228317      0.206249    232.465115
min        1.000000      0.444000      1.000000      0.000000  -6599.978000
25%     2549.250000     17.220000      2.000000      0.000000      1.760800
50%     5097.500000     53.910000      3.000000      0.200000      8.690000
75%     7645.750000    209.500000      5.000000      0.200000     29.297925
max    10194.000000  22638.480000     14.000000      0.800000   8399.976000

# Dataset understanding

In [14]:
# Numerical colmns
numerical_columns = df.select_dtypes(include=np.number).columns

print("Numerical Columns:")
print(numerical_columns)

Numerical Columns:
Index(['Row ID', 'Sales', 'Quantity', 'Discount', 'Profit'], dtype='object')

In [15]:
# Categorical columns

categorical_columns = df.select_dtypes(include='object').columns
print(categorical_columns)

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country/Region', 'City', 'State/Province',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name'],
      dtype='object')

In [16]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

# removing values

In [17]:
# Numbers of rows before removing null values
print("Rows before removing null values:",df.shape[0])

# Remove rows containing null values
df = df.dropna()

# Number of rows after removing null values
print("Rows after removing null values:",df.shape[0])

Rows before removing null values: 10194
Rows after removing null values: 10194

In [18]:
print("Number of duplicate rows:",df.duplicated().sum())

Number of duplicate rows: 0

In [19]:
df = df.drop_duplicates()

print("Dataset shape after removing duplicates:",df.shape)

Dataset shape after removing duplicates: (10194, 21)

In [20]:
# data cleaning and preprocessing
df["Order date"] = pd.to_datetime(df["Order Date"])
df["Ship date"] = pd.to_datetime(df["Ship Date"])
df[["Order date","Ship date"]].dtypes

Order date    datetime64[ns]
Ship date     datetime64[ns]
dtype: object

In [22]:
text_columns = ["Category","Sub-Category","Segment"]

for column in text_columns:
    df[column]=(
        df[column]
        .astype(str)
        .str.strip()
        .str.title()
    )

In [23]:
for column in text_columns:
    print("\n,column")
    print(df[column].unique())

,column
['Office Supplies' 'Furniture' 'Technology']

,column
['Paper' 'Binders' 'Labels' 'Storage' 'Art' 'Chairs' 'Fasteners' 'Phones'
 'Furnishings' 'Accessories' 'Bookcases' 'Envelopes' 'Appliances' 'Tables'
 'Supplies' 'Machines' 'Copiers']

,column
['Consumer' 'Home Office' 'Corporate']

In [24]:
# Final data check
print("Final shape:",df.shape)

print("\nTotal Missing Values:",df.isnull().sum().sum())

print("Total Duplicate Rows:",df.duplicated().sum())

print("\nData Types:")
print(df.dtypes)

Final shape: (10194, 23)

Total Missing Values: 0
Total Duplicate Rows: 0

Data Types:
Row ID                     int64
Order ID                  object
Order Date                object
Ship Date                 object
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Country/Region            object
City                      object
State/Province            object
Postal Code               object
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
Order date        datetime64[ns]
Ship date         datetime64[ns]
dtype: object

In [25]:
numerical_features = [
    "Sales",
    "Quantity",
    "Discount",
    "Profit"
]

df[numerical_features].describe()

              Sales      Quantity      Discount        Profit
count  10194.000000  10194.000000  10194.000000  10194.000000
mean     228.225854      3.791838      0.155385     28.673417
std      619.906839      2.228317      0.206249    232.465115
min        0.444000      1.000000      0.000000  -6599.978000
25%       17.220000      2.000000      0.000000      1.760800
50%       53.910000      3.000000      0.200000      8.690000
75%      209.500000      5.000000      0.200000     29.297925
max    22638.480000     14.000000      0.800000   8399.976000

In [26]:
summary = pd.DataFrame({
    "Mean":df[numerical_features].mean(),
    "Median":df[numerical_features].median(),
    "Minmum":df[numerical_features].min(),
    "Maximum":df[numerical_features].max(),
    "Standard Devation":df[numerical_features].std()
})

summary

                Mean  Median    Minmum    Maximum  Standard Devation
Sales     228.225854   53.91     0.444  22638.480         619.906839
Quantity    3.791838    3.00     1.000     14.000           2.228317
Discount    0.155385    0.20     0.000      0.800           0.206249
Profit     28.673417    8.69 -6599.978   8399.976         232.465115

# Sales and profit Analysis

In [27]:
# Category wise sale
category_sales = (
    df.groupby("Category")["Sales"]
   .sum()
   .sort_values(ascending=False)
)

category_sales

Category
Technology         839893.2790
Furniture          754747.7613
Office Supplies    731893.3140
Name: Sales, dtype: float64

In [28]:
# Category wise profit
category_profit = (
    df.groupby("Category")["Sales"]
   .sum()
   .sort_values(ascending=False)
)

category_profit

Category
Technology         839893.2790
Furniture          754747.7613
Office Supplies    731893.3140
Name: Sales, dtype: float64

In [29]:
# Sub category wise profit
sub_category_profit = (
    df.groupby("Category")["Sales"]
   .sum()
   .sort_values(ascending=False)
)

sub_category_profit

Category
Technology         839893.2790
Furniture          754747.7613
Office Supplies    731893.3140
Name: Sales, dtype: float64

In [1]:
print(""" BUSINESS INSIGHTS =Questions & Answers
The objective of EDA is to convert numerical results and visualizations into meaningful business insights.

Q1. Which category has the highest sales?
A: Technology has the highest sales.

Q2. Which category has the lowest sales?
A: Office Supplies has the lowest sales.

Q3. Which region contributes most to sales?
A: West Region.

PROFIT:

Q: Which category has highest profit?
A: Technology

Q: Which sub-categories have low/negative profit?
A: Tables 

Q: Which regions are most profitable?
A: West


DISCOUNT:

Q: Does profit decrease as discount increases?
A: Yes

Q: Which discount levels have poor profitability?
A: 40%-80% discount

Q: Which transactions generate negative profit?
A: Orders with >20% discount

CORRELATION 
Q1. Which variables have strong positive correlation?
A: Sales & Profit 

Q2. Which variables have negative correlation?
A: Discount & Profit Margin.
Q3. Is discount negatively related to Profit?
A: Yes, proved by heatmap.
""")

 BUSINESS INSIGHTS =Questions & Answers
The objective of EDA is to convert numerical results and visualizations into meaningful business insights.

Q1. Which category has the highest sales?
A: Technology has the highest sales.

Q2. Which category has the lowest sales?
A: Office Supplies has the lowest sales.

Q3. Which region contributes most to sales?
A: West Region.

PROFIT:

Q: Which category has highest profit?
A: Technology

Q: Which sub-categories have low/negative profit?
A: Tables

Q: Which regions are most profitable?
A: West


DISCOUNT:

Q: Does profit decrease as discount increases?
A: Yes

Q: Which discount levels have poor profitability?
A: 40%-80% discount

Q: Which transactions generate negative profit?
A: Orders with >20% discount

CORRELATION
Q1. Which variables have strong positive correlation?
A: Sales & Profit

Q2. Which variables have negative correlation?
A: Discount & Profit Margin.
Q3. Is discount negatively related to Profit?
A: Yes, proved by heatmap.

In [2]:
print(""" REPORT 
The Sample Superstore Sales Dataset contains 9,994 rows and 21 columns, covering retail transactions from 2014 to 2017.
The data was cleaned, and date columns were converted into datetime format. Exploratory Data Analysis (EDA) was performed using bar charts, boxplots,
scatter plots, and correlation analysis to understand sales, profit, and discount patterns. Technology recorded the highest sales of approximately $839,893
and the highest profit of $146,543,
while Furniture generated relatively low profit of $19,729 despite its substantial sales. The West region was the leading contributor to sales, with approximately $739,813.
Correlation analysis indicated a strong negative relationship between Discount and Profit Margin, with a reported correlation of −0.86, suggesting that higher discounts are 
generally associated with lower profitability. The analysis highlights the importance of managing discounts, improving Furniture's profitability, and focusing on 
profitable product categories and regions.
Businesses should use data-driven decisions, 
monitor discount policies, and conduct further analysis before implementing major pricing changes.
""")

 REPORT
The Sample Superstore Sales Dataset contains 9,994 rows and 21 columns, covering retail transactions from 2014 to 2017.
The data was cleaned, and date columns were converted into datetime format. Exploratory Data Analysis (EDA) was performed using bar charts, boxplots,
scatter plots, and correlation analysis to understand sales, profit, and discount patterns. Technology recorded the highest sales of approximately $839,893
and the highest profit of $146,543,
while Furniture generated relatively low profit of $19,729 despite its substantial sales. The West region was the leading contributor to sales, with approximately $739,813.
Correlation analysis indicated a strong negative relationship between Discount and Profit Margin, with a reported correlation of −0.86, suggesting that higher discounts are
generally associated with lower profitability. The analysis highlights the importance of managing discounts, improving Furniture's profitability, and focusing on
profitable product categories and regions.
Businesses should use data-driven decisions,
monitor discount policies, and conduct further analysis before implementing major pricing changes.